// <auto-generated />
using System;
using LicoriceBack.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace LicoriceBack.Migrations
{
    [DbContext(typeof(LicoriceBackContext))]
    [Migration("20230605213943_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.5");

            modelBuilder.Entity("LicoriceBack.Models.Card", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("CubeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CubeId");

                    b.ToTable("Cars");
                });

            modelBuilder.Entity("LicoriceBack.Models.Cube", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("PassphraseHash")
                        .HasColumnType("TEXT");

                    b.Property<int?>("WallId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("WallId");

                    b.ToTable("Cubes");
                });

            modelBuilder.Entity("LicoriceBack.Models.Wall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreateAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Descriptions")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsPublic")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Key")
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Walls");
                });

            modelBuilder.Entity("LicoriceBack.Models.Card", b =>
                {
                    b.HasOne("LicoriceBack.Models.Cube", "Cube")
                        .WithMany("Cards")
                        .HasForeignKey("CubeId");

                    b.Navigation("Cube");
                });

            modelBuilder.Entity("LicoriceBack.Models.Cube", b =>
                {
                    b.HasOne("LicoriceBack.Models.Wall", "Wall")
                        .WithMany("Cubes")
                        .HasForeignKey("WallId");

                    b.Navigation("Wall");
                });

            modelBuilder.Entity("LicoriceBack.Models.Cube", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("LicoriceBack.Models.Wall", b =>
                {
                    b.Navigation("Cubes");
                });
#pragma warning restore 612, 618
        }
    }
}
